CREATE TABLE [dbo].[MT_VehicleInspection](
	[InspectionID] [int] IDENTITY(1,1) NOT NULL,
	[VehicleID] [int] NOT NULL,
	[OlejSilnikowyInspekcja] [bit] NULL,
	[OlejSilnikowyWymianaTak] [bit] NULL,
	[OlejSilnikowyWymianaNie] [bit] NULL,
	[FiltrOlejuInspekcja] [bit] NULL,
	[FiltrOlejuWymianaTak] [bit] NULL,
	[FiltrOlejuWymianaNie] [bit] NULL,
	[FiltrPowietrzaInspekcja] [bit] NULL,
	[FiltrPowietrzaWymianaTak] [bit] NULL,
	[FiltrPowietrzaWymianaNie] [bit] NULL,
	[FiltrPaliwaInspekcja] [bit] NULL,
	[FiltrPaliwaWymianaTak] [bit] NULL,
	[FiltrPaliwaWymianaNie] [bit] NULL,
	[KlockiSzczekiHamulcowePrzodInspekcja] [bit] NULL,
	[KlockiSzczekiHamulcowePrzodWymianaTak] [bit] NULL,
	[KlockiSzczekiHamulcowePrzodWymianaNie] [bit] NULL,
	[KlockiSzczekiHamulcoweTylInspekcja] [bit] NULL,
	[KlockiSzczekiHamulcoweTylWymianaTak] [bit] NULL,
	[KlockiSzczekiHamulcoweTyl2WymianaNie] [bit] NULL,
	[PlynHamulcowyInspekcja] [bit] NULL,
	[PlynHamulcowyWymianaTak] [bit] NULL,
	[PlynHamulcowyWymianaNie] [bit] NULL,
	[SwieceZaplonoweInspekcja] [bit] NULL,
	[SwieceZaplonoweWymianaTak] [bit] NULL,
	[SwieceZaplonowe2WymianaNie] [bit] NULL,
	[FajkiZaplonoweInspekcja] [bit] NULL,
	[FajkiZaplonoweWymianaTak] [bit] NULL,
	[FajkiZaplonoweWymianaNie] [bit] NULL,
	[PrzewodyWysNapieciaInspekcja] [bit] NULL,
	[PrzewodyWysNapieciaWymianaTak] [bit] NULL,
	[PrzewodyWysNapieciaWymianaNie] [bit] NULL,
	[PlynChlodzacyInspekcja] [bit] NULL,
	[PlynChlodzacyWymianaTak] [bit] NULL,
	[PlynChlodzacyWymianaNie] [bit] NULL,
	[OlejWprzednimZawieszeniuInspekcja] [bit] NULL,
	[OlejWprzednimZawieszeniuWymianaTak] [bit] NULL,
	[OlejWprzednimZawieszeniuWymianaNie] [bit] NULL,
	[UszczelniaczePrzedniegoZawieszeniaInspekcja] [bit] NULL,
	[UszczelniaczePrzedniegoZawieszeniaWymianaTak] [bit] NULL,
	[UszczelniaczePrzedniegoZawieszeniaWymianaNie] [bit] NULL,
	[ZestawNapedowyInspekcja] [bit] NULL,
	[ZestawNapedowyWymianaTak] [bit] NULL,
	[ZestawNapedowyWymianaNie] [bit] NULL,
	[ZaworyInspekcja] [bit] NULL,
	[ZaworyWymianaTak] [bit] NULL,
	[ZaworyWymianaNie] [bit] NULL,
	[LancuchNapinaczRozrzaduInspekcja] [bit] NULL,
	[LancuchNapinaczRozrzaduWymianaTak] [bit] NULL,
	[LancuchNapinaczRozrzaduWymianaNie] [bit] NULL,
	[LinkaGazuInspekcja] [bit] NULL,
	[LinkaGazuWymianaTak] [bit] NULL,
	[LinkaGazuWymianaNie] [bit] NULL,
	[LinkaSpedzeglaInspekcja] [bit] NULL,
	[LinkaSpedzeglaWymianaTak] [bit] NULL,
	[LinkaSpedzeglaWymianaNie] [bit] NULL,
	[LinkaHamulcaPrzodInspekcja] [bit] NULL,
	[LinkaHamulcaPrzodWymianaTak] [bit] NULL,
	[LinkaHamulcaPrzodWymianaNie] [bit] NULL,
	[LinkaHamulcaTylInspekcja] [bit] NULL,
	[LinkaHamulcaTylWymianaTak] [bit] NULL,
	[LinkaHamulcaTylWymianaNie] [bit] NULL,
	[LinkaObrotomierzaInspekcja] [bit] NULL,
	[LinkaObrotomierzaWymianaTak] [bit] NULL,
	[LinkaObrotomierzaWymianaNie] [bit] NULL,
	[LinkaPredkosciomierzaInspekcja] [bit] NULL,
	[LinkaPredkosciomierzaWymianaTak] [bit] NULL,
	[LinkaPredkosciomierzaWymianaNie] [bit] NULL,
	[SynchronizacjaInspekcja] [bit] NULL,
	[SynchronizacjaWymianaTak] [bit] NULL,
	[SynchronizacjaWymianaNie] [bit] NULL,
	[PrzepustnicaInspekcja] [bit] NULL,
	[PrzepustnicaWymianaTak] [bit] NULL,
	[PrzepustnicaWymianaNie] [bit] NULL,
	[Uwagi] [nvarchar](max) NULL,
	[CREDATE] [datetime] NULL,
	[CREUSER] [nvarchar](50) NULL,
	[UPDDATE] [datetime] NULL,
	[UPDUSER] [nvarchar](50) NULL,
 CONSTRAINT [PK_MT_VehicleInspection] PRIMARY KEY CLUSTERED 
(
	[InspectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


